title: My Tutorial Sample Example
author: Zohora Noor
email: znoor000@citymail.cuny.edu.com
description: > # this means to ignore newlines until "baseurl:"
  Zohore Noor's participation in the GitHub pages tutorial

# social links
twitter_username: #i don't have one lol
github_username:  znoor000

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
